# 실습
## python 기본

### 1. 구구단 출력함수 작성하기
아래와 같이 구구단을 출력하는 코드가 있다.

In [3]:
list99 = []
for j in range(1, 10):
    l = []
    for i in range(1, 10):
        l.append(i*j)
    list99.append(l)
print(list99)

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 4, 6, 8, 10, 12, 14, 16, 18], [3, 6, 9, 12, 15, 18, 21, 24, 27], [4, 8, 12, 16, 20, 24, 28, 32, 36], [5, 10, 15, 20, 25, 30, 35, 40, 45], [6, 12, 18, 24, 30, 36, 42, 48, 54], [7, 14, 21, 28, 35, 42, 49, 56, 63], [8, 16, 24, 32, 40, 48, 56, 64, 72], [9, 18, 27, 36, 45, 54, 63, 72, 81]]


이를 참고하여, 다음과 같은 결과를 프린트하는 함수 f99를 작성하라.
```
f99(3)
[3, 6, 9, ..., 27]

f99([4, 7])
[4, 8, 12, ..., 36]
[7, 14, 35, ..., 63]

f99(21)
0보다 크고 10보다 작은 값을 입력하세요.

f99([10, 7])
0보다 크고 10보다 작은 값을 입력하세요.
[7, 14, 35, ..., 63]
```

아래 코드를 참고하여 :

In [8]:
z = 5
y = [3, 4]
x = y
from collections.abc import Iterable
if isinstance(x, Iterable):
    for i in x:
        print(i)
else:
    print(x)

3
4


1. 2단, 7단 등을 출력하는 print99 함수를 만들고,
2. 예외처리를 하고, print99를 이용하여 최종처리를 하는 f99를 완성하세요.

In [ ]:
def print99(x):
    xlist = []
    # 아래 사항을 완성하세요.
    for i in range():
        pass
    print(xlist)

def f99(x):
    errorstring = "0보다 크고 10보다 작은 값을 입력하세요."
    # 아래 사항을 완성하세요.
    if condition:
        for j in x:
            if condition2:
                print99(j)
            else:
                print(errorstring)
    else:
        if conditon2:
            print99(x)
        else:
            print(errorstring)
    

In [ ]:
f99(3)
f99([4, 7])
f99(21)
f99([10, 7])

### 2 함수
리스트 x와 값 v를 받아서 v의 배수가 되는 모든 리스트 x의 성분을 담은 리스트를 출력하는 factors 함수를 작성하라. 만약 없다면 -1을 리턴하라.

즉:
```
factors([4, 9, 21, 7], 3)
[9, 21]

factors([4, 9, 21, 7], 11)
-1
```

우리가 작성한 seqsearchall 함수를 참고하라.
```python
def seqsearchall(l, target):
    ret = []
    isnot = 0
    for i in range(len(l)):
        if l[i] == target:
            ret.append(i)
            isnot = 1
        elif l[i] > target:
            if isnot == 1: return ret
            else: return -1
    return -1
```

In [ ]:
def factors(x, v):
    ret = []
    isnot = 0
    for i in range(len(x)):
        pass

In [ ]:
factors([4, 9, 21, 7], 3)

In [ ]:
factors([4, 9, 21, 7], 11)

## numpy, pandas
### 3 numpy
임의의 0 ~ 99의 정수 값을 갖는 5 x 5 shape의 array를 생성하고 열 평균과 행 평균, 대각성분의 평균을 구하시오.

In [38]:
import numpy as np
from numpy.random import randn

dd = np.random.randint(0, 100, size=(6, 5))
dd

array([[45, 39, 55, 56, 48],
       [78, 34, 99, 52, 32],
       [27, 64, 78, 58, 32],
       [91, 17, 13, 55, 25],
       [10, 31, 26, 22, 10],
       [97, 38, 18, 77, 91]])

In [43]:
y = dd.mean(axis=1) # 행 평균
x = dd.mean(axis=0)
z = df.trace() / df.shape[0]

AttributeError: 'DataFrame' object has no attribute 'trace'

In [41]:
y

array([48.6, 59. , 51.8, 40.2, 19.8, 64.2])

In [42]:
x

array([58.        , 37.16666667, 48.16666667, 53.33333333, 39.66666667])

### 4. pandas


excel_exam.xlsx 파일을 이용하여 반별 과목별 평균을 구하고, 반별 과목별로 반별 과목 평균보다 낮은 학생 id를 출력하라.


| class | math | english | science |
|-------|------|---------|---------|
| 1     | 2    | 1       | 3       |
| 1     | 1    | 4       | NaN     |
| 1     | NaN  | 2       | NaN     |
| 2     | 8    | 7       | 6       |
| 2     | 7    | 6       | 5       |

- 평균보다 높은 학생의 수는 절반일 수도, 그 보다 높거나, 낮을 수 있다.

In [5]:
import pandas
df = pandas.read_excel('excel_exam.xlsx', sep='\t')
df.head()

id  class  math  english  science
0   1      1    50       98       50
1   2      1    60       97       60
2   3      1    45       86       78
3   4      1    30       98       58
4   5      2    25       80       65

In [44]:
df.iloc[:,1:].groupby('class').mean()

math  english  science
class                         
1      46.25    94.75    61.50
2      61.25    84.25    58.25
3      45.00    86.50    39.25
4      56.75    84.75    55.00
5      78.00    74.25    83.25

In [6]:
math_mean = df.groupby('class')['math'].mean()
math_mean

class
1    46.25
2    61.25
3    45.00
4    56.75
5    78.00
Name: math, dtype: float64

In [8]:
sci_mean = df.groupby('class')['science'].mean()
sci_mean

class
1    61.50
2    58.25
3    39.25
4    55.00
5    83.25
Name: science, dtype: float64

In [20]:
eng_mean = df.groupby('class')['english'].mean()
eng_mean

class
1    94.75
2    84.25
3    86.50
4    84.75
5    74.25
Name: english, dtype: float64

In [25]:
for i in range(1,6):
    ans = df[(df['class'] == i) & (df.math < math_mean.loc[i])]['id']
    print(ans)

2    3
3    4
Name: id, dtype: int64
4    5
5    6
Name: id, dtype: int64
8    9
Name: id, dtype: int64
12    13
13    14
Name: id, dtype: int64
16    17
Name: id, dtype: int64


In [22]:
for i in range(1,6):
    ans = df[(df['class'] == i) & (df.english < eng_mean.loc[i])]['id']
    print(ans)

2    3
Name: id, dtype: int64
4    5
7    8
Name: id, dtype: int64
10    11
11    12
Name: id, dtype: int64
14    15
Name: id, dtype: int64
16    17
18    19
Name: id, dtype: int64


In [23]:
for i in range(1,6):
    ans = df[(df['class'] == i) & (df.science < sci_mean.loc[i])]['id']
    print(ans)

0    1
1    2
3    4
Name: id, dtype: int64
6    7
7    8
Name: id, dtype: int64
8      9
11    12
Name: id, dtype: int64
13    14
Name: id, dtype: int64
19    20
Name: id, dtype: int64


### 5. 시각화
tips 데이터에서 sex와 time 별로, 음식지불액 대비 팁의 비율을 구하고, 이를 시각화하라.